### ISSUE TITLE
"npm install" doesn't work

### ISSUE THREAD

**Issue by Holzknoten** [Matt-B/mpd-web-client#1]
Hi Matt,

i want to test your websurface.
My Knowlege of Raspberry/linux is like beginner.

i clone your "mpd-web-client"-Folder to may RPI.

i try to start "npm install"
-bash: npm: Command not found.

what i have to do befor?

sorry for my bad english.
by Holzknoten from Germany

**Comment by Matt-B** [comment]
Hi!

Sorry I didn't see this issue - this project is pretty incomplete and it still uses an insecure version of express.js, so I don't recommend using it in its current state. I don't use MPD anymore at home so haven't updated it for a while.

With regards to your original issue though - you'll need to install node.js/npm in order to be able to run the project (or any node.js project). If you're using Raspbian you'll need to get it using apt-get - something like the following should do the trick:

```sudo apt install nodejs```

Hope that helps, sorry again for not replying when you posted this.

Matt
